import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../core/constants/app_enums.dart';
import '../../core/services/image_storage_service.dart';
import '../../data/datasources/local/local_clothing_datasource.dart';
import '../../features/add_item/domain/usecases/add_item_usecase.dart';
import 'repository_providers.dart';

// ─── Service ────────────────────────────────────────────────────────────────

/// Provides the singleton [ImageStorageService] used for compressing and
/// persisting clothing item photos to the app's documents directory.
final imageStorageServiceProvider = Provider<ImageStorageService>(
  (ref) => ImageStorageService(),
);

// ─── Use Case ────────────────────────────────────────────────────────────────

/// Provides [AddItemUseCase] wired to the clothing repository and image
/// storage service.
final addItemUseCaseProvider = Provider<AddItemUseCase>((ref) {
  return AddItemUseCase(
    ref.watch(clothingRepositoryProvider) as LocalClothingDatasource,
    ref.watch(imageStorageServiceProvider),
  );
});

// ─── Tagging Form ────────────────────────────────────────────────────────────

/// Immutable state for the item tagging form.
class TaggingFormState {
  final ClothingCategory? category;
  final ClothingSeason? season;
  final ClothingOccasion? occasion;
  final EmotionalTag emotionalTag;

  /// Selected subcategory within the chosen [category].
  final ClothingSubcategory? subcategory;

  /// Shoe formality; only relevant when [category] is [ClothingCategory.shoes].
  final ShoeFormality? shoeFormality;

  /// Coord-set UUID if the user links this item to an existing set; otherwise
  /// `null` (a new UUID is generated by the use case when [isCoordPiece] is true).
  final String? setId;

  /// Whether this item is part of a co-ord set.
  final bool isCoordPiece;

  /// `'top'` or `'bottom'` — which piece of the coord set this item represents.
  final String? coordPieceType;

  const TaggingFormState({
    this.category,
    this.season,
    this.occasion,
    this.emotionalTag = EmotionalTag.none,
    this.subcategory,
    this.shoeFormality,
    this.setId,
    this.isCoordPiece = false,
    this.coordPieceType,
  });

  /// `true` when all required fields are populated.
  ///
  /// * All categories require: category, season, occasion.
  /// * Shoes additionally require: shoeFormality.
  /// * One-piece additionally requires: subcategory.
  /// * Coord pieces additionally require: coordPieceType.
  bool get isValid {
    if (category == null || season == null || occasion == null) return false;
    if (category == ClothingCategory.shoes && shoeFormality == null) {
      return false;
    }
    if (category == ClothingCategory.onePiece && subcategory == null) {
      return false;
    }
    if (isCoordPiece && coordPieceType == null) return false;
    return true;
  }

  /// Returns a copy with selected fields replaced.
  ///
  /// Pass [clearSubcategory] or [clearShoeFormality] as `true` to explicitly
  /// reset nullable fields that cannot be set via the standard `?? this.x` pattern.
  TaggingFormState copyWith({
    ClothingCategory? category,
    ClothingSeason? season,
    ClothingOccasion? occasion,
    EmotionalTag? emotionalTag,
    ClothingSubcategory? subcategory,
    ShoeFormality? shoeFormality,
    String? setId,
    bool? isCoordPiece,
    String? coordPieceType,
    bool clearSubcategory = false,
    bool clearShoeFormality = false,
    bool clearCoordPieceType = false,
  }) {
    return TaggingFormState(
      category: category ?? this.category,
      season: season ?? this.season,
      occasion: occasion ?? this.occasion,
      emotionalTag: emotionalTag ?? this.emotionalTag,
      subcategory: clearSubcategory ? null : (subcategory ?? this.subcategory),
      shoeFormality:
          clearShoeFormality ? null : (shoeFormality ?? this.shoeFormality),
      setId: setId ?? this.setId,
      isCoordPiece: isCoordPiece ?? this.isCoordPiece,
      coordPieceType:
          clearCoordPieceType ? null : (coordPieceType ?? this.coordPieceType),
    );
  }
}

/// Manages the mutable state of the item tagging form.
class TaggingFormNotifier extends Notifier<TaggingFormState> {
  @override
  TaggingFormState build() => const TaggingFormState();

  /// Updates the selected clothing category, resetting subcategory and
  /// shoeFormality since they are category-specific.
  void setCategory(ClothingCategory value) {
    state = TaggingFormState(
      category: value,
      season: state.season,
      occasion: state.occasion,
      emotionalTag: state.emotionalTag,
      isCoordPiece: state.isCoordPiece,
      coordPieceType: state.coordPieceType,
    );
  }

  /// Updates the selected season.
  void setSeason(ClothingSeason value) =>
      state = state.copyWith(season: value);

  /// Updates the selected occasion.
  void setOccasion(ClothingOccasion value) =>
      state = state.copyWith(occasion: value);

  /// Updates the optional emotional tag.
  void setEmotionalTag(EmotionalTag value) =>
      state = state.copyWith(emotionalTag: value);

  /// Updates the selected subcategory.
  void setSubcategory(ClothingSubcategory value) =>
      state = state.copyWith(subcategory: value);

  /// Updates the shoe formality selection.
  void setShoeFormality(ShoeFormality value) =>
      state = state.copyWith(shoeFormality: value);

  /// Marks the item as a coord-set piece, optionally linking it to an
  /// [existingSetId].
  void setAsCoordPiece(String? existingSetId) {
    state = state.copyWith(isCoordPiece: true, setId: existingSetId);
  }

  /// Sets the coord piece type to `'top'` or `'bottom'`.
  void setCoordPieceType(String type) =>
      state = state.copyWith(coordPieceType: type);

  /// Removes the coord-set link from this item.
  void clearCoordLink() {
    state = TaggingFormState(
      category: state.category,
      season: state.season,
      occasion: state.occasion,
      emotionalTag: state.emotionalTag,
      subcategory: state.subcategory,
      shoeFormality: state.shoeFormality,
    );
  }

  /// Resets all fields to their initial (null) values.
  void reset() => state = const TaggingFormState();
}

/// StateNotifier provider for the tagging form used on [ItemTaggingScreen].
final taggingFormProvider =
    NotifierProvider<TaggingFormNotifier, TaggingFormState>(
  TaggingFormNotifier.new,
);
